...\"
...\" @OSF_COPYRIGHT@
...\" COPYRIGHT NOTICE
...\" Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
...\" ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
...\" src directory for the full copyright text.
...\"
...\"
...\" HISTORY
...\" $Log: 3o_example_01.idl,v $
...\" Revision 1.1.4.3  1993/01/29  17:19:07  cjd
...\" 	Embedded copyright notice
...\" 	[1993/01/29  17:02:49  cjd]
...\"
...\" Revision 1.1.4.2  1992/09/01  16:29:57  weir
...\" 	Moved
...\" 	[1992/09/01  16:21:55  weir]
...\" 
...\" Revision 1.1.2.2  1992/03/06  16:32:52  steiner
...\" 	Replaced comment leader - doc not source
...\" 	[1992/03/06  15:33:49  steiner]
...\" 
...\" Revision 1.1  1992/01/29  15:41:05  damon
...\" 	Initial revision
...\" 
...\" $EndLog$
...\"
[
uuid(3d6ead56-06e3-11ca-8dd1-826901beabcd),
version(1.0)
]
interface INTERFACENAME
{

}
