# Copyright 1991,1992,1993 Open Software Foundation, Inc.,
# Cambridge, Massachusetts
# All rights reserved.
#
#
# @OSF_FREE_COPYRIGHT@
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.2.5  1994/06/24  15:14:37  fred
# 	free copyright
# 	[1994/06/23  20:20:22  fred]
#
# Revision 1.1.2.4  1994/06/23  18:38:28  fred
# 	free copyright
# 	[1994/06/22  19:06:08  fred]
# 
# Revision 1.1.2.3  1993/04/10  01:35:19  bowe
# 	Add OSF copyright.
# 	[1993/04/10  01:32:04  bowe]
# 
# Revision 1.1.2.2  1992/07/15  14:34:41  bowe
# 	Initial rev.
# 	[1992/07/15  14:33:07  bowe]
# 
# $EndLog$
# 
# $Header: /u1/rcs/dte/doc/style.gd/Makefile,v 1.1.2.5 1994/06/24 15:14:37 fred Exp $

# No actions to do here.

all:
	echo "No action for $@"
install:
	echo "No action for $@"
clean:
clobber:

