/* Generated by IDL compiler version OSF DCE T1.1.0-03 */
#ifndef DCEAPI 
# include <dce/dcedef.h> 
#endif 
#ifndef POS_CMR_v0_0_included
#define POS_CMR_v0_0_included
#ifndef IDL_DOUBLE_USED
#define IDL_DOUBLE_USED
#endif
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef pos_def_v0_0_included
#include <pos_def.h>
#endif
extern void  DCEAPI CMR_STUB(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_long_int in_area_code,
    /* [in] */ idl_long_int in_phone_no,
    /* [in] */ idl_ushort_int cmr_len,
    /* [out] */ idl_long_int *appl_time,
    /* [out] */ CUST_DATA_IDL *cmr_buf,
    /* [out] */ idl_long_int *new_think_time,
    /* [out] */ idl_ulong_int *new_auth_lvl,
    /* [out] */ idl_ushort_int *flag_1,
    /* [out] */ idl_ushort_int *flag_2,
    /* [out] */ idl_ushort_int *flag_3,
    /* [out] */ idl_ushort_int *flag_4,
    /* [out] */ idl_ushort_int *flag_5,
    /* [out] */ idl_ushort_int *flag_6,
    /* [out] */ idl_ushort_int *flag_7,
    /* [out] */ idl_ushort_int *flag_8
#endif
);
extern void  DCEAPI KILL_CMR(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding
#endif
);
extern void  DCEAPI CNTRL_STUB(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_ushort_int flag_1,
    /* [in] */ idl_ushort_int flag_2,
    /* [in] */ idl_ushort_int flag_3,
    /* [in] */ idl_ushort_int flag_4,
    /* [in] */ idl_ushort_int flag_5,
    /* [in] */ idl_ushort_int flag_6,
    /* [in] */ idl_ushort_int flag_7,
    /* [in] */ idl_ushort_int flag_8,
    /* [in] */ idl_long_int think_time,
    /* [in] */ idl_ulong_int auth_lvl,
    /* [out] */ idl_long_float *CSPM
#endif
);
typedef struct POS_CMR_v0_0_epv_t {
void (* DCEAPI CMR_STUB)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_long_int in_area_code,
    /* [in] */ idl_long_int in_phone_no,
    /* [in] */ idl_ushort_int cmr_len,
    /* [out] */ idl_long_int *appl_time,
    /* [out] */ CUST_DATA_IDL *cmr_buf,
    /* [out] */ idl_long_int *new_think_time,
    /* [out] */ idl_ulong_int *new_auth_lvl,
    /* [out] */ idl_ushort_int *flag_1,
    /* [out] */ idl_ushort_int *flag_2,
    /* [out] */ idl_ushort_int *flag_3,
    /* [out] */ idl_ushort_int *flag_4,
    /* [out] */ idl_ushort_int *flag_5,
    /* [out] */ idl_ushort_int *flag_6,
    /* [out] */ idl_ushort_int *flag_7,
    /* [out] */ idl_ushort_int *flag_8
#endif
);
void (* DCEAPI KILL_CMR)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding
#endif
);
void (* DCEAPI CNTRL_STUB)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_ushort_int flag_1,
    /* [in] */ idl_ushort_int flag_2,
    /* [in] */ idl_ushort_int flag_3,
    /* [in] */ idl_ushort_int flag_4,
    /* [in] */ idl_ushort_int flag_5,
    /* [in] */ idl_ushort_int flag_6,
    /* [in] */ idl_ushort_int flag_7,
    /* [in] */ idl_ushort_int flag_8,
    /* [in] */ idl_long_int think_time,
    /* [in] */ idl_ulong_int auth_lvl,
    /* [out] */ idl_long_float *CSPM
#endif
);
} POS_CMR_v0_0_epv_t;
extern rpc_if_handle_t POS_CMR_v0_0_c_ifspec;
extern rpc_if_handle_t POS_CMR_v0_0_s_ifspec;

#ifdef __cplusplus
    }
#endif

#endif
