/* Generated by IDL compiler version OSF DCE T1.1.0-03 */
#ifndef DCEAPI 
# include <dce/dcedef.h> 
#endif 
#ifndef POS_PTQ_v0_0_included
#define POS_PTQ_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef pos_def_v0_0_included
#include <pos_def.h>
#endif
extern void  DCEAPI PTQ_STUB(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_long_int in_key,
    /* [in] */ idl_ushort_int ptq_len,
    /* [out] */ idl_long_int *appl_time,
    /* [out] */ ITEM_ROW_IDL *ptq_buf
#endif
);
extern void  DCEAPI KILL_PTQ(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding
#endif
);
typedef struct POS_PTQ_v0_0_epv_t {
void (* DCEAPI PTQ_STUB)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_long_int in_key,
    /* [in] */ idl_ushort_int ptq_len,
    /* [out] */ idl_long_int *appl_time,
    /* [out] */ ITEM_ROW_IDL *ptq_buf
#endif
);
void (* DCEAPI KILL_PTQ)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding
#endif
);
} POS_PTQ_v0_0_epv_t;
extern rpc_if_handle_t POS_PTQ_v0_0_c_ifspec;
extern rpc_if_handle_t POS_PTQ_v0_0_s_ifspec;

#ifdef __cplusplus
    }
#endif

#endif
