/** PTQ_IDL.IDL ******************************************************/
/*** IBM Corporation                                               ***/
/*** OS/2-AIX PSP Systems Performance                              ***/
/*** Department 57LS                                               ***/
/*** 11400 Burnet Road                                             ***/
/*** Austin Texas 78759                                            ***/
/*** Bob Russell, ZIP 9151                                         ***/
/*** (512) 838-0844 TL 678-0844                                    ***/
/*** robert_russell@vnet.ibm.com                                   ***/
/*********************************************************************/
/*****************************************************************************
 * COPYRIGHT:                                                                *
 * ----------                                                                *
 * Copyright (C) International Business Machines Corp., 1993,1994,1995,1996. *
 *                                                                           *
 * DISCLAIMER OF WARRANTIES:                                                 *
 * -------------------------                                                 *
 * The following [enclosed] code is sample code created by IBM               *
 * Corporation.  This sample code is not part of any standard IBM product    *
 * and is provided to you solely for the purpose of assisting you in the     *
 * development of your applications.  The code is provided "AS IS",          *
 * without warranty of any kind.  IBM shall not be liable for any damages    *
 * arising out of your use of the sample code, even if they have been        *
 * advised of the possibility of such damages.                               *
 *****************************************************************************/
/****************************************************************************
 * 09/02/92       Russell  Initial Creation
 * 11/28/92       Russell  Completed Test and Debug of PTQ
 * 12/11/92       Russell  Completed Initial code for Catalog Retrival
 * 09/16/93       Russell  begin splitting into distributed stubs

#define IN [in]
#define OUT [out]
 ****************************************************************************/


[
    uuid(334A2E24-0000-0000-0D00-379834000002),
    version(0)
]

interface POS_PTQ
{
     import "pos_def.idl";

    [idempotent]                     /* Price Table Lookup */
    void PTQ_STUB
    (
        [in]  handle_t                       hBinding,
        [in]  long                           in_key,
        [in]  unsigned short                 ptq_len,
        [out] long                           *appl_time,
        [out] ITEM_ROW_IDL                   *ptq_buf
    );

    [idempotent]                     /* Server Stop Listening */
    void KILL_PTQ
    (
        [in] handle_t       hBinding
    );

}
