...\" Copyright 1991,1992,1993 Open Software Foundation, Inc.,
...\" Cambridge, Massachusetts
...\" All rights reserved.
...\"
...\" @OSF_FREE_COPYRIGHT@
...\"
...\" HISTORY
...\" $Log: dman.1,v $
...\" Revision 1.1.2.5  1994/06/24  15:16:39  fred
...\" 	free copyright
...\" 	[1994/06/23  20:16:26  fred]
...\"
...\" Revision 1.1.2.4  1994/06/23  18:40:39  fred
...\" 	free copyright
...\" 	[1994/06/22  19:35:37  fred]
...\" 
...\" Revision 1.1.2.3  1993/04/10  01:23:01  bowe
...\" 	Add OSF copyright.
...\" 	[1993/04/10  01:20:52  bowe]
...\" 
...\" Revision 1.1.2.2  1992/07/07  22:26:37  bowe
...\" 	Initial rev.
...\" 	[1992/07/07  22:24:39  bowe]
...\" 
...\" $EndLog$
...\" $Header: /u1/rcs/dte/doc/user.gd/dman.1,v 1.1.2.5 1994/06/24 15:16:39 fred Exp $
...\"
.TH dman 1
.SH NAME
dman \- format manual pages
.SH SYNOPSIS
.B dman
[ \fB-n\fP | \fB-t\fP | \fB-x\fP ] [ \fB-sml\fP ]
[ \fB-T\fItypesetter\fP ] [ \fB-D\fIsymbol\fP ...] [-showifdef]
[ -libdir \fIdirectory\fP ]
[ \fB-help\fP ]
.I file ...
.SH DESCRIPTION
.PP
.B dman
.SH "OPTIONS"
.TP 8
.B -t
formats with \fItroff\fP and produces PostScript output.
.TP 8
.B -n
formats with \fInroff\fP (default).
.TP 8
.B -x
formats with \fItroff\fP but prepares a file that can be used by the
\fIExpress\fP page previewer.
.TP 8
.B -sml
use the RSML macros instead of plain -man
.TP 8
.B -T\fItypesetter\fP
if using troff, use \fItypesetter\fP (default \fIps\fP)
.TP 8
.B -libdir \fIdirectory\fP
set root directory of DTE library (default $DTE_LIBDIR, if set,
or /project/tools/libdata)
.TP
.B -D\fIsymbol\fP
pipe document source through \fBrmifdef\fP, defining \fIsymbol\fP.
As many of these as desired may be used.
.TP
.B -showifdef
Show all #if, #ifdef, #else, and #endif directives by making them bold and
surrounding them by a small amount of vertical space.
This option disables all #ifdef processing with rmifdef.
.TP
.B -help
prints a help message.
.PP
Multiple \fIfiles\fP may be specified, or a \fB-\fP may be used to read
standard input.
.PP
All preprocessors (\fItbl\fP, \fIeqn\fP, etc.) are used, although,
eventually, only the required preprocessors will be invoked.
.PP
This command uses the Documenter's Workbench versions
of the formatting tools and macros, with some minor OSF extensions.
These extensions include header files that define
some appearance extensions to the default macros.
