...\" Copyright 1991,1992,1993 Open Software Foundation, Inc.,
...\" Cambridge, Massachusetts
...\" All rights reserved.
...\"
...\" @OSF_FREE_COPYRIGHT@
...\"
...\" HISTORY
...\" $Log: ix-density.1,v $
...\" Revision 1.1.2.5  1994/06/24  15:49:29  fred
...\" 	free copyright
...\" 	[1994/06/24  15:44:05  fred]
...\"
...\" Revision 1.1.2.4  1994/06/23  18:42:41  fred
...\" 	free copyright
...\" 	[1994/06/22  20:18:34  fred]
...\" 
...\" Revision 1.1.2.3  1993/04/10  00:18:02  bowe
...\" 	Add OSF copyright.
...\" 	[1993/04/10  00:17:00  bowe]
...\" 
...\" Revision 1.1.2.2  1992/12/03  15:14:04  bowe
...\" 	Initial revision.
...\" 	[1992/12/03  15:13:19  bowe]
...\" 
...\" $EndLog$
...\" $Header: /u1/rcs/dte/util/ix-density.1,v 1.1.2.5 1994/06/24 15:49:29 fred Exp $
...\"
.TH ix-density 1
.SH NAME
ix-density \- checks index densities in DTE book parts.
.SH SYNOPSIS
.B ix-density
[ \fB-desc \fIfile\fP ] [ \fB-sync \fIdirectory\fP ]
[ \fB-tbl\fP ] [ \fB-h\fP ]
.SH DESCRIPTION
.PP
.B ix-density
checks and reports on the index densities of parts in
a DTE book directory.  It does this by reading the contents
of the \fBSync\fP directory in the book directory.  To
use this command go to the book directory you want to check,
and use the following command:
.sp
.in +5n
\fBcd /project/books/book-directory\fP
\fBix-density\fP

\f(CWIndex Density for /project/books/book-directory

                           # OF      INDEX      INDEX
PART NAME                 PAGES    ENTRIES    DENSITY
title                         2          0       0.00
preface                       6          5       0.83
ch01                         16         19       1.19
ch02                         13          4       0.31
    \&.
    \&.
    \&.
.in -5n
.SH "OPTIONS"
.TP 8
.B -desc
Specifies a description file other than the default file, "Description."
.TP 8
.B -sync
Specifies a sync directory other than the default directory, "Sync."
.TP 8
.B -tbl
Causes ix-density to produce tabular output suitable for processing
with \fBtbl\fP.
For example, use the following command line:
.sp
.in +5n
\fBix-density -tbl | dmm - | lpr\fP
.in -5n
.TP 8
.B -help
prints a help message.

