<!--
# COPYRIGHT NOTICE
# Copyright (c) 1990-1996 Open Software Foundation, Inc. 
# ALL RIGHTS RESERVED (DCE). See the file named COPYRIGHT.DCE in the 
# src directory for the full copyright text. 
# 
# 
# HISTORY
# $Log: sample.idl,v $
# Revision 1.1.2.3  1996/12/17  20:49:42  damon
# 	Expanded OSF C O P Y R I G H T   N O T I C E
# 	[1996/12/17  20:46:53  damon]
#
# Revision 1.1.2.2  1996/11/21  16:54:29  weir
# 	Minor corrections
# 	[1996/11/21  16:53:55  weir]
# 
# Revision 1.1.2.1  1996/11/21  16:43:04  weir
# 	Initial submission
# 	[1996/11/21  16:42:07  weir]
# 
# $EndLog$
# 
-->
/****************************************************************************/
/* [27.VI.94]                                                               */
/*                                                                          */
/* sample.idl --                                                            */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*                            -77 cols-                                     */
/****************************************************************************/



[
uuid(002d70b2-671b-1d24-a1da-0000c0d4de56),
version(1.0)
]
interface sample
{

	const long int TEXT_SIZE = 100;


	void sample_call(
		[in] handle_t binding,
		[out] long *status,
		[in,out] error_status_t *remote_status);

	void sample_get_text(
		[in] handle_t binding,
		[in] uuid_t object_uuid,
		[in,out,string] char text[TEXT_SIZE],
		[out] long *status,
		[in,out] error_status_t *remote_status);

	void sample_put_text(
		[in] handle_t binding,
		[in] uuid_t object_uuid,
		[in,out,string] char text[TEXT_SIZE],
		[out] long *status,
		[in,out] error_status_t *remote_status);


}

