<!--
# COPYRIGHT NOTICE
# Copyright (c) 1990-1996 Open Software Foundation, Inc. 
# ALL RIGHTS RESERVED (DCE). See the file named COPYRIGHT.DCE in the 
# src directory for the full copyright text. 
# 
# 
# HISTORY
# $Log: sample_bind.idl,v $
# Revision 1.1.2.3  1996/12/17  20:49:45  damon
# 	Expanded OSF C O P Y R I G H T   N O T I C E
# 	[1996/12/17  20:46:58  damon]
#
# Revision 1.1.2.2  1996/11/21  16:54:31  weir
# 	Minor corrections
# 	[1996/11/21  16:53:57  weir]
# 
# Revision 1.1.2.1  1996/11/21  16:43:08  weir
# 	Initial submission
# 	[1996/11/21  16:42:10  weir]
# 
# $EndLog$
# 
-->
/****************************************************************************/
/* [27.VI.94]                                                               */
/*                                                                          */
/* sample_bind.idl --                                                       */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*                            -77 cols-                                     */
/****************************************************************************/


[
uuid(006868ca-6064-1d49-9829-0000c0d4de56),
version(1.0)
]
interface sample_bind
{

	void rs_bind_to_object(
		[in] handle_t binding,
		[in, string] char *component,
		[out] uuid_t *object_uuid, 
		[out] uuid_t *mgr_type_uuid,
		[out] error_status_t *status
	);
}

