/** CMR_IDL.IDL ******************************************************/
/*** IBM Corporation                                               ***/
/*** OS/2-AIX PSP Systems Performance                              ***/
/*** Department 57LS                                               ***/
/*** 11400 Burnet Road                                             ***/
/*** Austin Texas 78759                                            ***/
/*** Bob Russell, ZIP 9151                                         ***/
/*** (512) 838-0844 TL 678-0844                                    ***/
/*** robert_russell@vnet.ibm.com                                   ***/
/*********************************************************************/
/*****************************************************************************
 * COPYRIGHT:                                                                *
 * ----------                                                                *
 * Copyright (C) International Business Machines Corp., 1993,1994,1995,1996. *
 *                                                                           *
 * DISCLAIMER OF WARRANTIES:                                                 *
 * -------------------------                                                 *
 * The following [enclosed] code is sample code created by IBM               *
 * Corporation.  This sample code is not part of any standard IBM product    *
 * and is provided to you solely for the purpose of assisting you in the     *
 * development of your applications.  The code is provided "AS IS",          *
 * without warranty of any kind.  IBM shall not be liable for any damages    *
 * arising out of your use of the sample code, even if they have been        *
 * advised of the possibility of such damages.                               *
 *****************************************************************************/
/****************************************************************************
 * 09/02/92       Russell  Initial Creation
 * 11/28/92       Russell  Completed Test and Debug of PTQ
 * 12/11/92       Russell  Completed Initial code for Catalog Retrival
 * 09/16/93       Russell  begin splitting into distributed stubs

#define IN [in]
#define OUT [out]
 ****************************************************************************/


[
    uuid(334A2E24-0000-0000-0D00-379834000003),
    version(0)
]

interface POS_CMR
{
    import "pos_def.idl";

    [idempotent]                     /* Price Table Lookup */
    void CMR_STUB
    (
        [in]  handle_t                       hBinding,
        [in]  long                           in_area_code,
        [in]  long                           in_phone_no,
        [in]  unsigned short                 cmr_len,
        [out] long                           *appl_time,
        [out] CUST_DATA_IDL                  *cmr_buf,
        [out] long                            *new_think_time,
        [out] unsigned long                   *new_auth_lvl,
        [out]  unsigned short                 *flag_1,
        [out]  unsigned short                 *flag_2,
        [out]  unsigned short                 *flag_3,
        [out]  unsigned short                 *flag_4,
        [out]  unsigned short                 *flag_5,
        [out]  unsigned short                 *flag_6,
        [out]  unsigned short                 *flag_7,
        [out]  unsigned short                 *flag_8
    );

    [idempotent]                     /* Server Stop Listening */
    void KILL_CMR
    (
        [in] handle_t       hBinding
    );

    void CNTRL_STUB
    (
        [in]  handle_t                       hBinding,
        [in]  unsigned short                 flag_1,
        [in]  unsigned short                 flag_2,
        [in]  unsigned short                 flag_3,
        [in]  unsigned short                 flag_4,
        [in]  unsigned short                 flag_5,
        [in]  unsigned short                 flag_6,
        [in]  unsigned short                 flag_7,
        [in]  unsigned short                 flag_8,
        [in]  long                           think_time,
        [in]  unsigned long                  auth_lvl,
        [out] double                         *CSPM
    );

}
