/* Generated by IDL compiler version OSF DCE T1.1.0-03 */
#ifdef VMS
#pragma nostandard
#endif
#include <pos_idl.h>
#include <dce/idlddefs.h>

static rpc_syntax_id_t IDL_transfer_syntaxes[1] = {
{
{0x8a885d04, 0x1ceb, 0x11c9, 0x9f, 0xe8, {0x8, 0x0, 0x2b, 0x10, 0x48, 0x60}},
2}};

static rpc_if_rep_t IDL_ifspec = {
  1, /* ifspec rep version */
  8, /* op count */
  0, /* if version */
  {0x334a2e24, 0x0000, 0x0000, 0x0d, 0x00, {0x37, 0x98, 0x34, 0x4, 0x0, 0x0}},
  2, /* stub/rt if version */
  {0, NULL}, /* endpoint vector */
  {1, IDL_transfer_syntaxes} /* syntax vector */
};
/* global */ rpc_if_handle_t PointOfSale_v0_0_c_ifspec = (rpc_if_handle_t)&IDL_ifspec;
static idl_ulong_int IDL_offset_vec[] = {
0,
sizeof(SAVE_DATA_IDL ),
offsetof(SAVE_DATA_IDL , trans_no.dept_no),
offsetof(SAVE_DATA_IDL , trans_no.trans_date),
offsetof(SAVE_DATA_IDL , trans_no.trans_time),
offsetof(SAVE_DATA_IDL , trans_no.reg_no),
offsetof(SAVE_DATA_IDL , trans_header.acct_id),
offsetof(SAVE_DATA_IDL , trans_header.line_item_cnt),
offsetof(SAVE_DATA_IDL , trans_header.item_cnt),
offsetof(SAVE_DATA_IDL , trans_header.trans_type),
offsetof(SAVE_DATA_IDL , trans_header.paymt_type),
offsetof(SAVE_DATA_IDL , trans_header.employee_no),
offsetof(SAVE_DATA_IDL , trans_header.cust_ref),
offsetof(SAVE_DATA_IDL , trans_header.padding),
offsetof(SAVE_DATA_IDL , line_item),
sizeof(LINE_ITEM_IDL ),
offsetof(LINE_ITEM_IDL , item_no),
offsetof(LINE_ITEM_IDL , qty),
offsetof(LINE_ITEM_IDL , price_each),
offsetof(LINE_ITEM_IDL , price_total),
offsetof(LINE_ITEM_IDL , descr),
offsetof(LINE_ITEM_IDL , padding),
sizeof(CUST_DATA_IDL ),
offsetof(CUST_DATA_IDL , area_code),
offsetof(CUST_DATA_IDL , phone_no),
offsetof(CUST_DATA_IDL , extn),
offsetof(CUST_DATA_IDL , acct_id),
offsetof(CUST_DATA_IDL , cust_last_name),
offsetof(CUST_DATA_IDL , cust_first_name),
offsetof(CUST_DATA_IDL , cust_MI),
offsetof(CUST_DATA_IDL , ship_addr),
offsetof(CUST_DATA_IDL , mail_addr),
offsetof(CUST_DATA_IDL , state),
offsetof(CUST_DATA_IDL , city),
offsetof(CUST_DATA_IDL , zip_code),
offsetof(CUST_DATA_IDL , cust_type),
offsetof(CUST_DATA_IDL , disc_pcnt),
offsetof(CUST_DATA_IDL , tax_pcnt),
offsetof(CUST_DATA_IDL , drv_lic),
offsetof(CUST_DATA_IDL , drv_lic_state),
offsetof(CUST_DATA_IDL , date_last_purch),
offsetof(CUST_DATA_IDL , cust_ref),
offsetof(CUST_DATA_IDL , cust_filler),
sizeof(ITEM_ROW_IDL ),
offsetof(ITEM_ROW_IDL , item_no),
offsetof(ITEM_ROW_IDL , upc_no),
offsetof(ITEM_ROW_IDL , descr),
offsetof(ITEM_ROW_IDL , dept_no),
offsetof(ITEM_ROW_IDL , qty_on_hand),
offsetof(ITEM_ROW_IDL , inv_unit),
offsetof(ITEM_ROW_IDL , ord_at_qty),
offsetof(ITEM_ROW_IDL , qty_to_ord),
offsetof(ITEM_ROW_IDL , inv_cnt),
offsetof(ITEM_ROW_IDL , inv_date),
offsetof(ITEM_ROW_IDL , qty_on_ord),
offsetof(ITEM_ROW_IDL , lst_ord_dt),
offsetof(ITEM_ROW_IDL , price_1),
offsetof(ITEM_ROW_IDL , eff_dt_1),
offsetof(ITEM_ROW_IDL , price_2),
offsetof(ITEM_ROW_IDL , eff_dt_2),
offsetof(ITEM_ROW_IDL , price_3),
offsetof(ITEM_ROW_IDL , eff_dt_3),
offsetof(ITEM_ROW_IDL , unit_cost),
0
};

static void (*IDL_rtn_vec[])() = {
(void (*)())NULL,
(void (*)())NULL
};

static idl_byte IDL_type_vec[] = {
0xff,0xff,0xff,0xff,
1,
0,
0xff,0xff,
0x03,0x00,
0x01,0x00,
0x00,0x00,
0x00,0x00,
0x24,0x2e,0x4a,0x33,
0x00,0x00,
0x00,0x00,
0x0d,
0x00,
0x37,0x98,0x34,0x04,0x00,0x00,
0x00,0x00,0x00,0x00,
0x04,0x00,0x00,0x00,
0x68,0x09,0x00,0x00,
0xff,0xff,0xff,0xff,
0xff,0xff,0xff,0xff,
0xff,0xff,0xff,0xff,
0xff,0xff,0xff,0xff,
0x08,0x00,0x00,0x00,
0x02,0x00,0x00,0x00,
0x06,0x00,0x00,0x00,
0x02,0x00,0x00,0x00,
0x00,0x01,0x00,0x00,
0x02,0x00,0x00,0x00,
0x10,0x01,0x00,0x00,
0x02,0x00,0x00,0x00,
0x09,0x00,0x00,0x00,
0x06,0x00,0x00,0x00,
0x28,0x01,0x00,0x00,
0x03,0x00,0x00,0x00,
0x70,0x01,0x00,0x00,
0x02,0x00,0x00,0x00,
0x11,0x00,0x00,0x00,
0x03,0x00,0x00,0x00,
0x94,0x01,0x00,0x00,
0x0c,0x00,0x00,0x00,
0xac,0x01,0x00,0x00,
0x02,0x00,0x00,0x00,
0x07,0x00,0x00,0x00,
0x03,0x00,0x00,0x00,
0x14,0x02,0x00,0x00,
0x02,0x00,0x00,0x00,
0x34,0x02,0x00,0x00,
0x02,0x00,0x00,0x00,
0x08,0x00,0x00,0x00,
0x06,0x00,0x00,0x00,
0x44,0x02,0x00,0x00,
0x00,0x00,0x00,0x00,
0xff,0xff,0xff,0xff,
0x02,0x00,0x00,0x00,
0x06,0x00,0x00,0x00,
0x04,0x00,0x00,0x00,
0x8c,0x02,0x00,0x00,
0x01,0x00,0x00,0x00,
0xc8,0x02,0x00,0x00,
0x02,0x00,0x00,0x00,
0x02,0x00,0x00,0x00,
0x00,0x00,0x00,0x00,
0xff,0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
0xff,0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
0x0d,0x00,0x00,0x00,
0x0a,0x00,0x00,0x00,
0xdc,0x02,0x00,0x00,
0x01,0x00,0x00,0x00,
0x2c,0x03,0x00,0x00,
0x02,0x00,0x00,0x00,
IDL_DT_LONG,
IDL_DT_EOL,
0xff,0xff,
0x03,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x04,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_LONG,
IDL_DT_EOL,
0xff,
0x05,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_FIXED_STRUCT,
0|IDL_PROP_DEP_CHAR|IDL_PROP_DEP_FLOAT|IDL_PROP_DEP_INT,
0xff,
0x34,0x03,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x02,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x03,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x04,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x05,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_OPEN_ARRAY,
0,
0xff,
0xa3,0x03,0x00,0x00,
0xa3,0x03,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x06,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,
0x08,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_ALLOCATE,
IDL_DT_CONF_ARRAY,
0,
0xc7,0x03,0x00,0x00,
0xc7,0x03,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x06,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,
0x07,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_LONG,
IDL_DT_EOL,
0xff,
0x08,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_CONF_ARRAY,
0,
0xff,
0xdb,0x03,0x00,0x00,
0xdb,0x03,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x02,0x00,0x00,0x00,
IDL_DT_LONG,
IDL_DT_EOL,
0xff,0xff,
0x03,0x00,0x00,0x00,
IDL_DT_LONG,
IDL_DT_EOL,
0xff,0xff,
0x04,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x05,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_LONG,
IDL_DT_EOL,
0xff,
0x06,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_FIXED_STRUCT,
0|IDL_PROP_DEP_CHAR|IDL_PROP_DEP_FLOAT|IDL_PROP_DEP_INT,
0xff,
0xf0,0x03,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x07,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_LONG,
IDL_DT_EOL,
0xff,
0x08,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_ULONG,
IDL_DT_EOL,
0xff,
0x09,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,
0x0a,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,
0x0b,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,
0x0c,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,
0x0d,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,
0x0e,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,
0x0f,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,
0x10,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,
0x02,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x03,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x05,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_FIXED_STRUCT,
0|IDL_PROP_DEP_CHAR|IDL_PROP_DEP_FLOAT|IDL_PROP_DEP_INT,
0xff,
0xa8,0x04,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x04,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_LONG,
IDL_DT_EOL,
0xff,
0x06,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_ULONG,
IDL_DT_EOL,
0xff,
0x02,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x03,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x04,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_OPEN_ARRAY,
0,
0xff,
0x1b,0x05,0x00,0x00,
0x1b,0x05,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x05,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x06,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x07,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_OPEN_ARRAY,
0,
0xff,
0x3f,0x05,0x00,0x00,
0x3f,0x05,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x02,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x03,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_STRING,
IDL_DT_OPEN_ARRAY,
0|IDL_PROP_DEP_CHAR,
0x63,0x05,0x00,0x00,
0x63,0x05,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x04,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x05,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_ALLOCATE,
IDL_DT_STRING,
IDL_DT_OPEN_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,0xff,0xff,
0x87,0x05,0x00,0x00,
0x87,0x05,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x05,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_STRING,
IDL_DT_OPEN_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xab,0x05,0x00,0x00,
0xab,0x05,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x02,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x03,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x04,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x05,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x06,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x07,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x08,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x09,0x00,0x00,0x00,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,0xff,
0x0a,0x00,0x00,0x00,
IDL_DT_LONG,
IDL_DT_EOL,
0xff,0xff,
0x0b,0x00,0x00,0x00,
IDL_DT_ULONG,
IDL_DT_EOL,
0xff,0xff,
0x0c,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_DOUBLE,
IDL_DT_EOL,
0xff,
0x2b,0x00,0x00,0x00,
IDL_DT_NDR_ALIGN_8,
IDL_DT_LONG,
IDL_DT_LONG,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,0xff,
0x4b,0x09,0x00,0x00,
0x4b,0x09,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0x2f,0x09,0x00,0x00,
0x2f,0x09,0x00,0x00,
IDL_DT_LONG,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0x13,0x09,0x00,0x00,
0x13,0x09,0x00,0x00,
IDL_DT_LONG,
IDL_DT_LONG,
IDL_DT_LONG,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,0xff,
0xf7,0x08,0x00,0x00,
0xf7,0x08,0x00,0x00,
IDL_DT_LONG,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xdb,0x08,0x00,0x00,
0xdb,0x08,0x00,0x00,
IDL_DT_DOUBLE,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xbf,0x08,0x00,0x00,
0xbf,0x08,0x00,0x00,
IDL_DT_DOUBLE,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xa3,0x08,0x00,0x00,
0xa3,0x08,0x00,0x00,
IDL_DT_DOUBLE,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0x87,0x08,0x00,0x00,
0x87,0x08,0x00,0x00,
IDL_DT_DOUBLE,
IDL_DT_EOL,
0xff,
1,
IDL_BOUND_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_BOUND_MAX_IS,
IDL_DT_USHORT,
0xff,0xff,
0x04,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_LAST_IS,
IDL_DT_USHORT,
0xff,0xff,
0x03,0x00,0x00,0x00,
IDL_DT_BYTE,
0xff,0xff,
1,
IDL_BOUND_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_BOUND_SIZE_IS,
IDL_DT_USHORT,
0xff,0xff,
0x06,0x00,0x00,0x00,
IDL_DT_BYTE,
0xff,0xff,
1,
IDL_BOUND_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_BOUND_SIZE_IS,
IDL_DT_USHORT,
0xff,0xff,
0x06,0x00,0x00,0x00,
IDL_DT_BYTE,
0xff,0xff,0xff,
0x16,0x00,0x00,0x00,
IDL_DT_NDR_ALIGN_8,
IDL_DT_LONG,
IDL_DT_LONG,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,0xff,
0x6b,0x08,0x00,0x00,
0x6b,0x08,0x00,0x00,
IDL_DT_LONG,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0x4f,0x08,0x00,0x00,
0x4f,0x08,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0x33,0x08,0x00,0x00,
0x33,0x08,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0x17,0x08,0x00,0x00,
0x17,0x08,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0xfb,0x07,0x00,0x00,
0xfb,0x07,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0xdf,0x07,0x00,0x00,
0xdf,0x07,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0xc3,0x07,0x00,0x00,
0xc3,0x07,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0xa7,0x07,0x00,0x00,
0xa7,0x07,0x00,0x00,
IDL_DT_LONG,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0x8b,0x07,0x00,0x00,
0x8b,0x07,0x00,0x00,
IDL_DT_DOUBLE,
IDL_DT_DOUBLE,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,0xff,0xff,
0x6f,0x07,0x00,0x00,
0x6f,0x07,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0x53,0x07,0x00,0x00,
0x53,0x07,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0x37,0x07,0x00,0x00,
0x37,0x07,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0x1b,0x07,0x00,0x00,
0x1b,0x07,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0xff,0x06,0x00,0x00,
0xff,0x06,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x01,0x00,0x00,0x00,
IDL_DT_NDR_ALIGN_8,
IDL_DT_NDR_ALIGN_4,
IDL_DT_BEGIN_NESTED_STRUCT,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,0xff,
0xe3,0x06,0x00,0x00,
0xe3,0x06,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0xc7,0x06,0x00,0x00,
0xc7,0x06,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0xab,0x06,0x00,0x00,
0xab,0x06,0x00,0x00,
IDL_DT_LONG,
IDL_DT_END_NESTED_STRUCT,
IDL_DT_NDR_ALIGN_4,
IDL_DT_BEGIN_NESTED_STRUCT,
IDL_DT_LONG,
IDL_DT_LONG,
IDL_DT_LONG,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,0xff,
0x8f,0x06,0x00,0x00,
0x8f,0x06,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0x73,0x06,0x00,0x00,
0x73,0x06,0x00,0x00,
IDL_DT_LONG,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0x57,0x06,0x00,0x00,
0x57,0x06,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0x3b,0x06,0x00,0x00,
0x3b,0x06,0x00,0x00,
IDL_DT_END_NESTED_STRUCT,
IDL_DT_FIXED_ARRAY,
0|IDL_PROP_DEP_CHAR|IDL_PROP_DEP_FLOAT|IDL_PROP_DEP_INT,
0xff,
0xcf,0x05,0x00,0x00,
0xcf,0x05,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,
1,
IDL_BOUND_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_BOUND_MAX_IS,
IDL_DT_USHORT,
0xff,0xff,
0x03,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_LAST_IS,
IDL_DT_USHORT,
0xff,0xff,
0x02,0x00,0x00,0x00,
IDL_DT_BYTE,
0xff,0xff,
1,
IDL_BOUND_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_BOUND_MAX_IS,
IDL_DT_USHORT,
0xff,0xff,
0x06,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_LAST_IS,
IDL_DT_USHORT,
0xff,0xff,
0x05,0x00,0x00,0x00,
IDL_DT_BYTE,
0xff,0xff,
1,
IDL_BOUND_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_BOUND_MAX_IS,
IDL_DT_USHORT,
0xff,0xff,
0x02,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
IDL_BOUND_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_BOUND_MAX_IS,
IDL_DT_USHORT,
0xff,0xff,
0x04,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
IDL_BOUND_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_BOUND_MAX_IS,
IDL_DT_USHORT,
0xff,0xff,
0x04,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x03,0x00,0x00,0x00,
IDL_DT_FIXED_STRUCT,
0|IDL_PROP_DEP_CHAR|IDL_PROP_DEP_FLOAT|IDL_PROP_DEP_INT,
0xff,0xff,
0xe0,0x05,0x00,0x00,
0x0f,0x00,0x00,0x00,
IDL_DT_NDR_ALIGN_8,
IDL_DT_LONG,
IDL_DT_LONG,
IDL_DT_DOUBLE,
IDL_DT_DOUBLE,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0x1f,0x06,0x00,0x00,
0x1f,0x06,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0x03,0x06,0x00,0x00,
0x03,0x06,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x13,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x23,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x97,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x47,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x07,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x07,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x08,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x08,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x03,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x53,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x47,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x0b,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x03,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x17,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x03,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x2f,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x03,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x47,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x47,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x03,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x17,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x2f,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x07,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x0b,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x0b,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x0b,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x0b,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x0b,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x07,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x03,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x23,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,0xff,
0x00,0x00,0x00,0x10,
0
};


void rpc_PTQ
#ifdef IDL_PROTOTYPES
(
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_long_int in_key,
    /* [in] */ idl_ushort_int ptq_len,
    /* [out] */ idl_long_int *appl_time,
    /* [out] */ ITEM_ROW_IDL *ptq_buf
)
#else
(hBinding, in_key, ptq_len, appl_time, ptq_buf)
#endif

#ifndef IDL_PROTOTYPES
    handle_t hBinding;
    idl_long_int in_key;
    idl_ushort_int ptq_len;
    idl_long_int *appl_time;
    ITEM_ROW_IDL *ptq_buf;
#endif
{
rpc_transfer_syntax_t IDL_transfer_syntax;
rpc_iovector_elt_t IDL_outs;
volatile ndr_ulong_int IDL_fault_code=error_status_ok;
volatile ndr_ulong_int IDL_user_fault_id;
volatile RPC_SS_THREADS_CANCEL_STATE_T IDL_async_cancel_state;
IDL_ms_t IDL_ms;
idl_byte IDL_stack_packet[IDL_STACK_PACKET_SIZE];
rpc_void_p_t IDL_param_vec[6];

RPC_SS_INIT_CLIENT
RPC_SS_THREADS_DISABLE_ASYNC(IDL_async_cancel_state);
rpc_ss_init_marsh_state(IDL_type_vec, &IDL_ms);
IDL_ms.IDL_stack_packet_status = IDL_stack_packet_unused_k;
IDL_ms.IDL_stack_packet_addr = IDL_stack_packet;
TRY
IDL_ms.IDL_call_h = 0;
IDL_ms.IDL_elt_p = NULL;
IDL_ms.IDL_offset_vec = IDL_offset_vec;
IDL_ms.IDL_rtn_vec = IDL_rtn_vec;
IDL_param_vec[1] = (rpc_void_p_t)&hBinding;
IDL_param_vec[2] = (rpc_void_p_t)&in_key;
IDL_param_vec[3] = (rpc_void_p_t)&ptq_len;
IDL_param_vec[4] = (rpc_void_p_t)appl_time;
IDL_param_vec[5] = (rpc_void_p_t)ptq_buf;
IDL_ms.IDL_param_vec = IDL_param_vec;
IDL_ms.IDL_side = IDL_client_side_k;
IDL_ms.IDL_language = IDL_lang_c_k;
rpc_call_start((rpc_binding_handle_t) hBinding, 0|rpc_c_call_idempotent,
 (rpc_if_handle_t)&IDL_ifspec,0,(rpc_call_handle_t*)&IDL_ms.IDL_call_h,&IDL_transfer_syntax,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok) goto IDL_closedown;
rpc_ss_ndr_marsh_interp(
    2,
    256,
    IDL_param_vec, &IDL_ms);
IDL_ms.IDL_elt_p = &IDL_outs;
rpc_call_transceive((rpc_call_handle_t)IDL_ms.IDL_call_h,(rpc_iovector_p_t)&IDL_ms.IDL_iovec,
  IDL_ms.IDL_elt_p,&IDL_ms.IDL_drep,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok)
{
IDL_ms.IDL_elt_p = NULL;
goto IDL_closedown;
}
rpc_ss_ndr_unmar_interp(
    2,
    272,
    IDL_param_vec, &IDL_ms);
IDL_closedown: ;
CATCH(rpc_x_ss_pipe_comm_error)
FINALLY
rpc_ss_ndr_clean_up(&IDL_ms);
rpc_ss_call_end_2((rpc_call_handle_t *)&IDL_ms.IDL_call_h,&IDL_fault_code,&IDL_user_fault_id,&IDL_ms.IDL_status);
if (IDL_ms.IDL_mem_handle.memory)
{
 rpc_ss_mem_free(&IDL_ms.IDL_mem_handle);
}
rpc_ss_report_error_2(IDL_fault_code,IDL_user_fault_id,IDL_ms.IDL_status,
 (RPC_SS_THREADS_CANCEL_STATE_T *)&IDL_async_cancel_state, NULL, NULL, NULL, &IDL_ms);
RPC_SS_THREADS_RESTORE_ASYNC(IDL_async_cancel_state);
ENDTRY
}

void rpc_CAT
#ifdef IDL_PROTOTYPES
(
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_ushort_int catalog_code,
    /* [in] */ idl_ushort_int sizname,
    /* [in] */ idl_ushort_int maxname,
    /* [in] */ idl_byte filename[],
    /* [in, out] */ idl_ushort_int *cat_len,
    /* [out] */ idl_long_int *appl_time,
    /* [out] */ idl_byte *cat_buf
)
#else
(hBinding, catalog_code, sizname, maxname, filename, cat_len, appl_time, cat_buf)
#endif

#ifndef IDL_PROTOTYPES
    handle_t hBinding;
    idl_ushort_int catalog_code;
    idl_ushort_int sizname;
    idl_ushort_int maxname;
    idl_byte filename[];
    idl_ushort_int *cat_len;
    idl_long_int *appl_time;
    idl_byte *cat_buf;
#endif
{
rpc_transfer_syntax_t IDL_transfer_syntax;
rpc_iovector_elt_t IDL_outs;
volatile ndr_ulong_int IDL_fault_code=error_status_ok;
volatile ndr_ulong_int IDL_user_fault_id;
volatile RPC_SS_THREADS_CANCEL_STATE_T IDL_async_cancel_state;
IDL_ms_t IDL_ms;
idl_byte IDL_stack_packet[IDL_STACK_PACKET_SIZE];
rpc_void_p_t IDL_param_vec[9];

RPC_SS_INIT_CLIENT
RPC_SS_THREADS_DISABLE_ASYNC(IDL_async_cancel_state);
rpc_ss_init_marsh_state(IDL_type_vec, &IDL_ms);
IDL_ms.IDL_stack_packet_status = IDL_stack_packet_unused_k;
IDL_ms.IDL_stack_packet_addr = IDL_stack_packet;
TRY
IDL_ms.IDL_call_h = 0;
IDL_ms.IDL_elt_p = NULL;
IDL_ms.IDL_offset_vec = IDL_offset_vec;
IDL_ms.IDL_rtn_vec = IDL_rtn_vec;
IDL_param_vec[1] = (rpc_void_p_t)&hBinding;
IDL_param_vec[2] = (rpc_void_p_t)&catalog_code;
IDL_param_vec[3] = (rpc_void_p_t)&sizname;
IDL_param_vec[4] = (rpc_void_p_t)&maxname;
IDL_param_vec[5] = (rpc_void_p_t)filename;
IDL_param_vec[6] = (rpc_void_p_t)cat_len;
IDL_param_vec[7] = (rpc_void_p_t)appl_time;
IDL_param_vec[8] = (rpc_void_p_t)cat_buf;
IDL_ms.IDL_param_vec = IDL_param_vec;
IDL_ms.IDL_side = IDL_client_side_k;
IDL_ms.IDL_language = IDL_lang_c_k;
rpc_call_start((rpc_binding_handle_t) hBinding, 0|rpc_c_call_idempotent,
 (rpc_if_handle_t)&IDL_ifspec,1,(rpc_call_handle_t*)&IDL_ms.IDL_call_h,&IDL_transfer_syntax,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok) goto IDL_closedown;
rpc_ss_ndr_marsh_interp(
    5,
    296,
    IDL_param_vec, &IDL_ms);
IDL_ms.IDL_elt_p = &IDL_outs;
rpc_call_transceive((rpc_call_handle_t)IDL_ms.IDL_call_h,(rpc_iovector_p_t)&IDL_ms.IDL_iovec,
  IDL_ms.IDL_elt_p,&IDL_ms.IDL_drep,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok)
{
IDL_ms.IDL_elt_p = NULL;
goto IDL_closedown;
}
rpc_ss_ndr_unmar_interp(
    3,
    368,
    IDL_param_vec, &IDL_ms);
IDL_closedown: ;
CATCH(rpc_x_ss_pipe_comm_error)
FINALLY
rpc_ss_ndr_clean_up(&IDL_ms);
rpc_ss_call_end_2((rpc_call_handle_t *)&IDL_ms.IDL_call_h,&IDL_fault_code,&IDL_user_fault_id,&IDL_ms.IDL_status);
if (IDL_ms.IDL_mem_handle.memory)
{
 rpc_ss_mem_free(&IDL_ms.IDL_mem_handle);
}
rpc_ss_report_error_2(IDL_fault_code,IDL_user_fault_id,IDL_ms.IDL_status,
 (RPC_SS_THREADS_CANCEL_STATE_T *)&IDL_async_cancel_state, NULL, NULL, NULL, &IDL_ms);
RPC_SS_THREADS_RESTORE_ASYNC(IDL_async_cancel_state);
ENDTRY
}

void rpc_CMR
#ifdef IDL_PROTOTYPES
(
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_long_int in_area_code,
    /* [in] */ idl_long_int in_phone_no,
    /* [in] */ idl_ushort_int cmr_len,
    /* [out] */ idl_long_int *appl_time,
    /* [out] */ CUST_DATA_IDL *cmr_buf,
    /* [out] */ idl_long_int *new_think_time,
    /* [out] */ idl_ulong_int *new_auth_lvl,
    /* [out] */ idl_ushort_int *flag_1,
    /* [out] */ idl_ushort_int *flag_2,
    /* [out] */ idl_ushort_int *flag_3,
    /* [out] */ idl_ushort_int *flag_4,
    /* [out] */ idl_ushort_int *flag_5,
    /* [out] */ idl_ushort_int *flag_6,
    /* [out] */ idl_ushort_int *flag_7,
    /* [out] */ idl_ushort_int *flag_8
)
#else
(hBinding, in_area_code, in_phone_no, cmr_len, appl_time, cmr_buf, new_think_time, new_auth_lvl, flag_1, flag_2, flag_3, flag_4, flag_5, flag_6, flag_7, flag_8)
#endif

#ifndef IDL_PROTOTYPES
    handle_t hBinding;
    idl_long_int in_area_code;
    idl_long_int in_phone_no;
    idl_ushort_int cmr_len;
    idl_long_int *appl_time;
    CUST_DATA_IDL *cmr_buf;
    idl_long_int *new_think_time;
    idl_ulong_int *new_auth_lvl;
    idl_ushort_int *flag_1;
    idl_ushort_int *flag_2;
    idl_ushort_int *flag_3;
    idl_ushort_int *flag_4;
    idl_ushort_int *flag_5;
    idl_ushort_int *flag_6;
    idl_ushort_int *flag_7;
    idl_ushort_int *flag_8;
#endif
{
rpc_transfer_syntax_t IDL_transfer_syntax;
rpc_iovector_elt_t IDL_outs;
volatile ndr_ulong_int IDL_fault_code=error_status_ok;
volatile ndr_ulong_int IDL_user_fault_id;
volatile RPC_SS_THREADS_CANCEL_STATE_T IDL_async_cancel_state;
IDL_ms_t IDL_ms;
idl_byte IDL_stack_packet[IDL_STACK_PACKET_SIZE];
rpc_void_p_t IDL_param_vec[17];

RPC_SS_INIT_CLIENT
RPC_SS_THREADS_DISABLE_ASYNC(IDL_async_cancel_state);
rpc_ss_init_marsh_state(IDL_type_vec, &IDL_ms);
IDL_ms.IDL_stack_packet_status = IDL_stack_packet_unused_k;
IDL_ms.IDL_stack_packet_addr = IDL_stack_packet;
TRY
IDL_ms.IDL_call_h = 0;
IDL_ms.IDL_elt_p = NULL;
IDL_ms.IDL_offset_vec = IDL_offset_vec;
IDL_ms.IDL_rtn_vec = IDL_rtn_vec;
IDL_param_vec[1] = (rpc_void_p_t)&hBinding;
IDL_param_vec[2] = (rpc_void_p_t)&in_area_code;
IDL_param_vec[3] = (rpc_void_p_t)&in_phone_no;
IDL_param_vec[4] = (rpc_void_p_t)&cmr_len;
IDL_param_vec[5] = (rpc_void_p_t)appl_time;
IDL_param_vec[6] = (rpc_void_p_t)cmr_buf;
IDL_param_vec[7] = (rpc_void_p_t)new_think_time;
IDL_param_vec[8] = (rpc_void_p_t)new_auth_lvl;
IDL_param_vec[9] = (rpc_void_p_t)flag_1;
IDL_param_vec[10] = (rpc_void_p_t)flag_2;
IDL_param_vec[11] = (rpc_void_p_t)flag_3;
IDL_param_vec[12] = (rpc_void_p_t)flag_4;
IDL_param_vec[13] = (rpc_void_p_t)flag_5;
IDL_param_vec[14] = (rpc_void_p_t)flag_6;
IDL_param_vec[15] = (rpc_void_p_t)flag_7;
IDL_param_vec[16] = (rpc_void_p_t)flag_8;
IDL_ms.IDL_param_vec = IDL_param_vec;
IDL_ms.IDL_side = IDL_client_side_k;
IDL_ms.IDL_language = IDL_lang_c_k;
rpc_call_start((rpc_binding_handle_t) hBinding, 0|rpc_c_call_idempotent,
 (rpc_if_handle_t)&IDL_ifspec,2,(rpc_call_handle_t*)&IDL_ms.IDL_call_h,&IDL_transfer_syntax,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok) goto IDL_closedown;
rpc_ss_ndr_marsh_interp(
    3,
    404,
    IDL_param_vec, &IDL_ms);
IDL_ms.IDL_elt_p = &IDL_outs;
rpc_call_transceive((rpc_call_handle_t)IDL_ms.IDL_call_h,(rpc_iovector_p_t)&IDL_ms.IDL_iovec,
  IDL_ms.IDL_elt_p,&IDL_ms.IDL_drep,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok)
{
IDL_ms.IDL_elt_p = NULL;
goto IDL_closedown;
}
rpc_ss_ndr_unmar_interp(
    12,
    428,
    IDL_param_vec, &IDL_ms);
IDL_closedown: ;
CATCH(rpc_x_ss_pipe_comm_error)
FINALLY
rpc_ss_ndr_clean_up(&IDL_ms);
rpc_ss_call_end_2((rpc_call_handle_t *)&IDL_ms.IDL_call_h,&IDL_fault_code,&IDL_user_fault_id,&IDL_ms.IDL_status);
if (IDL_ms.IDL_mem_handle.memory)
{
 rpc_ss_mem_free(&IDL_ms.IDL_mem_handle);
}
rpc_ss_report_error_2(IDL_fault_code,IDL_user_fault_id,IDL_ms.IDL_status,
 (RPC_SS_THREADS_CANCEL_STATE_T *)&IDL_async_cancel_state, NULL, NULL, NULL, &IDL_ms);
RPC_SS_THREADS_RESTORE_ASYNC(IDL_async_cancel_state);
ENDTRY
}

void rpc_SAV
#ifdef IDL_PROTOTYPES
(
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_ushort_int in_len,
    /* [in] */ idl_ushort_int sendmax,
    /* [out] */ idl_long_int *appl_time,
    /* [in] */ SAVE_DATA_IDL *sendbuf,
    /* [out] */ idl_ulong_int *ret_code
)
#else
(hBinding, in_len, sendmax, appl_time, sendbuf, ret_code)
#endif

#ifndef IDL_PROTOTYPES
    handle_t hBinding;
    idl_ushort_int in_len;
    idl_ushort_int sendmax;
    idl_long_int *appl_time;
    SAVE_DATA_IDL *sendbuf;
    idl_ulong_int *ret_code;
#endif
{
rpc_transfer_syntax_t IDL_transfer_syntax;
rpc_iovector_elt_t IDL_outs;
volatile ndr_ulong_int IDL_fault_code=error_status_ok;
volatile ndr_ulong_int IDL_user_fault_id;
volatile RPC_SS_THREADS_CANCEL_STATE_T IDL_async_cancel_state;
IDL_ms_t IDL_ms;
idl_byte IDL_stack_packet[IDL_STACK_PACKET_SIZE];
rpc_void_p_t IDL_param_vec[7];

RPC_SS_INIT_CLIENT
RPC_SS_THREADS_DISABLE_ASYNC(IDL_async_cancel_state);
rpc_ss_init_marsh_state(IDL_type_vec, &IDL_ms);
IDL_ms.IDL_stack_packet_status = IDL_stack_packet_unused_k;
IDL_ms.IDL_stack_packet_addr = IDL_stack_packet;
TRY
IDL_ms.IDL_call_h = 0;
IDL_ms.IDL_elt_p = NULL;
IDL_ms.IDL_offset_vec = IDL_offset_vec;
IDL_ms.IDL_rtn_vec = IDL_rtn_vec;
IDL_param_vec[1] = (rpc_void_p_t)&hBinding;
IDL_param_vec[2] = (rpc_void_p_t)&in_len;
IDL_param_vec[3] = (rpc_void_p_t)&sendmax;
IDL_param_vec[4] = (rpc_void_p_t)appl_time;
IDL_param_vec[5] = (rpc_void_p_t)sendbuf;
IDL_param_vec[6] = (rpc_void_p_t)ret_code;
IDL_ms.IDL_param_vec = IDL_param_vec;
IDL_ms.IDL_side = IDL_client_side_k;
IDL_ms.IDL_language = IDL_lang_c_k;
rpc_call_start((rpc_binding_handle_t) hBinding, 0|rpc_c_call_idempotent,
 (rpc_if_handle_t)&IDL_ifspec,3,(rpc_call_handle_t*)&IDL_ms.IDL_call_h,&IDL_transfer_syntax,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok) goto IDL_closedown;
rpc_ss_ndr_marsh_interp(
    3,
    532,
    IDL_param_vec, &IDL_ms);
IDL_ms.IDL_elt_p = &IDL_outs;
rpc_call_transceive((rpc_call_handle_t)IDL_ms.IDL_call_h,(rpc_iovector_p_t)&IDL_ms.IDL_iovec,
  IDL_ms.IDL_elt_p,&IDL_ms.IDL_drep,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok)
{
IDL_ms.IDL_elt_p = NULL;
goto IDL_closedown;
}
rpc_ss_ndr_unmar_interp(
    2,
    564,
    IDL_param_vec, &IDL_ms);
IDL_closedown: ;
CATCH(rpc_x_ss_pipe_comm_error)
FINALLY
rpc_ss_ndr_clean_up(&IDL_ms);
rpc_ss_call_end_2((rpc_call_handle_t *)&IDL_ms.IDL_call_h,&IDL_fault_code,&IDL_user_fault_id,&IDL_ms.IDL_status);
if (IDL_ms.IDL_mem_handle.memory)
{
 rpc_ss_mem_free(&IDL_ms.IDL_mem_handle);
}
rpc_ss_report_error_2(IDL_fault_code,IDL_user_fault_id,IDL_ms.IDL_status,
 (RPC_SS_THREADS_CANCEL_STATE_T *)&IDL_async_cancel_state, NULL, NULL, NULL, &IDL_ms);
RPC_SS_THREADS_RESTORE_ASYNC(IDL_async_cancel_state);
ENDTRY
}

void file_tran
#ifdef IDL_PROTOTYPES
(
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_ushort_int sizname,
    /* [in] */ idl_ushort_int maxname,
    /* [in] */ idl_byte filename[],
    /* [in] */ idl_ushort_int in_len,
    /* [in] */ idl_ushort_int sendmax,
    /* [in] */ idl_byte sendbuf[]
)
#else
(hBinding, sizname, maxname, filename, in_len, sendmax, sendbuf)
#endif

#ifndef IDL_PROTOTYPES
    handle_t hBinding;
    idl_ushort_int sizname;
    idl_ushort_int maxname;
    idl_byte filename[];
    idl_ushort_int in_len;
    idl_ushort_int sendmax;
    idl_byte sendbuf[];
#endif
{
rpc_transfer_syntax_t IDL_transfer_syntax;
rpc_iovector_elt_t IDL_outs;
volatile ndr_ulong_int IDL_fault_code=error_status_ok;
volatile ndr_ulong_int IDL_user_fault_id;
volatile RPC_SS_THREADS_CANCEL_STATE_T IDL_async_cancel_state;
IDL_ms_t IDL_ms;
idl_byte IDL_stack_packet[IDL_STACK_PACKET_SIZE];
rpc_void_p_t IDL_param_vec[8];

RPC_SS_INIT_CLIENT
RPC_SS_THREADS_DISABLE_ASYNC(IDL_async_cancel_state);
rpc_ss_init_marsh_state(IDL_type_vec, &IDL_ms);
IDL_ms.IDL_stack_packet_status = IDL_stack_packet_unused_k;
IDL_ms.IDL_stack_packet_addr = IDL_stack_packet;
TRY
IDL_ms.IDL_call_h = 0;
IDL_ms.IDL_elt_p = NULL;
IDL_ms.IDL_offset_vec = IDL_offset_vec;
IDL_ms.IDL_rtn_vec = IDL_rtn_vec;
IDL_param_vec[1] = (rpc_void_p_t)&hBinding;
IDL_param_vec[2] = (rpc_void_p_t)&sizname;
IDL_param_vec[3] = (rpc_void_p_t)&maxname;
IDL_param_vec[4] = (rpc_void_p_t)filename;
IDL_param_vec[5] = (rpc_void_p_t)&in_len;
IDL_param_vec[6] = (rpc_void_p_t)&sendmax;
IDL_param_vec[7] = (rpc_void_p_t)sendbuf;
IDL_ms.IDL_param_vec = IDL_param_vec;
IDL_ms.IDL_side = IDL_client_side_k;
IDL_ms.IDL_language = IDL_lang_c_k;
rpc_call_start((rpc_binding_handle_t) hBinding, 0|rpc_c_call_idempotent,
 (rpc_if_handle_t)&IDL_ifspec,4,(rpc_call_handle_t*)&IDL_ms.IDL_call_h,&IDL_transfer_syntax,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok) goto IDL_closedown;
rpc_ss_ndr_marsh_interp(
    6,
    580,
    IDL_param_vec, &IDL_ms);
IDL_ms.IDL_elt_p = &IDL_outs;
rpc_call_transceive((rpc_call_handle_t)IDL_ms.IDL_call_h,(rpc_iovector_p_t)&IDL_ms.IDL_iovec,
  IDL_ms.IDL_elt_p,&IDL_ms.IDL_drep,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok)
{
IDL_ms.IDL_elt_p = NULL;
goto IDL_closedown;
}
rpc_ss_ndr_unmar_interp(
    0,
    0,
    IDL_param_vec, &IDL_ms);
IDL_closedown: ;
CATCH(rpc_x_ss_pipe_comm_error)
FINALLY
rpc_ss_ndr_clean_up(&IDL_ms);
rpc_ss_call_end_2((rpc_call_handle_t *)&IDL_ms.IDL_call_h,&IDL_fault_code,&IDL_user_fault_id,&IDL_ms.IDL_status);
if (IDL_ms.IDL_mem_handle.memory)
{
 rpc_ss_mem_free(&IDL_ms.IDL_mem_handle);
}
rpc_ss_report_error_2(IDL_fault_code,IDL_user_fault_id,IDL_ms.IDL_status,
 (RPC_SS_THREADS_CANCEL_STATE_T *)&IDL_async_cancel_state, NULL, NULL, NULL, &IDL_ms);
RPC_SS_THREADS_RESTORE_ASYNC(IDL_async_cancel_state);
ENDTRY
}

void char_op
#ifdef IDL_PROTOTYPES
(
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_ushort_int in_len,
    /* [in] */ idl_char *sendbuf,
    /* [in] */ idl_ushort_int out_len,
    /* [out] */ idl_char *recvbuf
)
#else
(hBinding, in_len, sendbuf, out_len, recvbuf)
#endif

#ifndef IDL_PROTOTYPES
    handle_t hBinding;
    idl_ushort_int in_len;
    idl_char *sendbuf;
    idl_ushort_int out_len;
    idl_char *recvbuf;
#endif
{
rpc_transfer_syntax_t IDL_transfer_syntax;
rpc_iovector_elt_t IDL_outs;
volatile ndr_ulong_int IDL_fault_code=error_status_ok;
volatile ndr_ulong_int IDL_user_fault_id;
volatile RPC_SS_THREADS_CANCEL_STATE_T IDL_async_cancel_state;
IDL_ms_t IDL_ms;
idl_byte IDL_stack_packet[IDL_STACK_PACKET_SIZE];
rpc_void_p_t IDL_param_vec[6];

RPC_SS_INIT_CLIENT
RPC_SS_THREADS_DISABLE_ASYNC(IDL_async_cancel_state);
rpc_ss_init_marsh_state(IDL_type_vec, &IDL_ms);
IDL_ms.IDL_stack_packet_status = IDL_stack_packet_unused_k;
IDL_ms.IDL_stack_packet_addr = IDL_stack_packet;
TRY
IDL_ms.IDL_call_h = 0;
IDL_ms.IDL_elt_p = NULL;
IDL_ms.IDL_offset_vec = IDL_offset_vec;
IDL_ms.IDL_rtn_vec = IDL_rtn_vec;
IDL_param_vec[1] = (rpc_void_p_t)&hBinding;
IDL_param_vec[2] = (rpc_void_p_t)&in_len;
IDL_param_vec[3] = (rpc_void_p_t)sendbuf;
IDL_param_vec[4] = (rpc_void_p_t)&out_len;
IDL_param_vec[5] = (rpc_void_p_t)recvbuf;
IDL_ms.IDL_param_vec = IDL_param_vec;
IDL_ms.IDL_side = IDL_client_side_k;
IDL_ms.IDL_language = IDL_lang_c_k;
rpc_call_start((rpc_binding_handle_t) hBinding, 0|rpc_c_call_idempotent,
 (rpc_if_handle_t)&IDL_ifspec,5,(rpc_call_handle_t*)&IDL_ms.IDL_call_h,&IDL_transfer_syntax,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok) goto IDL_closedown;
rpc_ss_ndr_marsh_interp(
    3,
    652,
    IDL_param_vec, &IDL_ms);
IDL_ms.IDL_elt_p = &IDL_outs;
rpc_call_transceive((rpc_call_handle_t)IDL_ms.IDL_call_h,(rpc_iovector_p_t)&IDL_ms.IDL_iovec,
  IDL_ms.IDL_elt_p,&IDL_ms.IDL_drep,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok)
{
IDL_ms.IDL_elt_p = NULL;
goto IDL_closedown;
}
rpc_ss_ndr_unmar_interp(
    1,
    712,
    IDL_param_vec, &IDL_ms);
IDL_closedown: ;
CATCH(rpc_x_ss_pipe_comm_error)
FINALLY
rpc_ss_ndr_clean_up(&IDL_ms);
rpc_ss_call_end_2((rpc_call_handle_t *)&IDL_ms.IDL_call_h,&IDL_fault_code,&IDL_user_fault_id,&IDL_ms.IDL_status);
if (IDL_ms.IDL_mem_handle.memory)
{
 rpc_ss_mem_free(&IDL_ms.IDL_mem_handle);
}
rpc_ss_report_error_2(IDL_fault_code,IDL_user_fault_id,IDL_ms.IDL_status,
 (RPC_SS_THREADS_CANCEL_STATE_T *)&IDL_async_cancel_state, NULL, NULL, NULL, &IDL_ms);
RPC_SS_THREADS_RESTORE_ASYNC(IDL_async_cancel_state);
ENDTRY
}

void suicide
#ifdef IDL_PROTOTYPES
(
    /* [in] */ handle_t hBinding
)
#else
(hBinding)
#endif

#ifndef IDL_PROTOTYPES
    handle_t hBinding;
#endif
{
rpc_transfer_syntax_t IDL_transfer_syntax;
rpc_iovector_elt_t IDL_outs;
volatile ndr_ulong_int IDL_fault_code=error_status_ok;
volatile ndr_ulong_int IDL_user_fault_id;
volatile RPC_SS_THREADS_CANCEL_STATE_T IDL_async_cancel_state;
IDL_ms_t IDL_ms;
idl_byte IDL_stack_packet[IDL_STACK_PACKET_SIZE];
rpc_void_p_t IDL_param_vec[2];

RPC_SS_INIT_CLIENT
RPC_SS_THREADS_DISABLE_ASYNC(IDL_async_cancel_state);
rpc_ss_init_marsh_state(IDL_type_vec, &IDL_ms);
IDL_ms.IDL_stack_packet_status = IDL_stack_packet_unused_k;
IDL_ms.IDL_stack_packet_addr = IDL_stack_packet;
TRY
IDL_ms.IDL_call_h = 0;
IDL_ms.IDL_elt_p = NULL;
IDL_ms.IDL_offset_vec = IDL_offset_vec;
IDL_ms.IDL_rtn_vec = IDL_rtn_vec;
IDL_param_vec[1] = (rpc_void_p_t)&hBinding;
IDL_ms.IDL_param_vec = IDL_param_vec;
IDL_ms.IDL_side = IDL_client_side_k;
IDL_ms.IDL_language = IDL_lang_c_k;
rpc_call_start((rpc_binding_handle_t) hBinding, 0|rpc_c_call_idempotent,
 (rpc_if_handle_t)&IDL_ifspec,6,(rpc_call_handle_t*)&IDL_ms.IDL_call_h,&IDL_transfer_syntax,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok) goto IDL_closedown;
rpc_ss_ndr_marsh_interp(
    0,
    0,
    IDL_param_vec, &IDL_ms);
IDL_ms.IDL_elt_p = &IDL_outs;
rpc_call_transceive((rpc_call_handle_t)IDL_ms.IDL_call_h,(rpc_iovector_p_t)&IDL_ms.IDL_iovec,
  IDL_ms.IDL_elt_p,&IDL_ms.IDL_drep,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok)
{
IDL_ms.IDL_elt_p = NULL;
goto IDL_closedown;
}
rpc_ss_ndr_unmar_interp(
    0,
    0,
    IDL_param_vec, &IDL_ms);
IDL_closedown: ;
CATCH(rpc_x_ss_pipe_comm_error)
FINALLY
rpc_ss_ndr_clean_up(&IDL_ms);
rpc_ss_call_end_2((rpc_call_handle_t *)&IDL_ms.IDL_call_h,&IDL_fault_code,&IDL_user_fault_id,&IDL_ms.IDL_status);
if (IDL_ms.IDL_mem_handle.memory)
{
 rpc_ss_mem_free(&IDL_ms.IDL_mem_handle);
}
rpc_ss_report_error_2(IDL_fault_code,IDL_user_fault_id,IDL_ms.IDL_status,
 (RPC_SS_THREADS_CANCEL_STATE_T *)&IDL_async_cancel_state, NULL, NULL, NULL, &IDL_ms);
RPC_SS_THREADS_RESTORE_ASYNC(IDL_async_cancel_state);
ENDTRY
}

void pos_CNTRL
#ifdef IDL_PROTOTYPES
(
    /* [in] */ handle_t hBinding,
    /* [in] */ idl_ushort_int flag_1,
    /* [in] */ idl_ushort_int flag_2,
    /* [in] */ idl_ushort_int flag_3,
    /* [in] */ idl_ushort_int flag_4,
    /* [in] */ idl_ushort_int flag_5,
    /* [in] */ idl_ushort_int flag_6,
    /* [in] */ idl_ushort_int flag_7,
    /* [in] */ idl_ushort_int flag_8,
    /* [in] */ idl_long_int think_time,
    /* [in] */ idl_ulong_int auth_lvl,
    /* [out] */ idl_long_float *CSPM
)
#else
(hBinding, flag_1, flag_2, flag_3, flag_4, flag_5, flag_6, flag_7, flag_8, think_time, auth_lvl, CSPM)
#endif

#ifndef IDL_PROTOTYPES
    handle_t hBinding;
    idl_ushort_int flag_1;
    idl_ushort_int flag_2;
    idl_ushort_int flag_3;
    idl_ushort_int flag_4;
    idl_ushort_int flag_5;
    idl_ushort_int flag_6;
    idl_ushort_int flag_7;
    idl_ushort_int flag_8;
    idl_long_int think_time;
    idl_ulong_int auth_lvl;
    idl_long_float *CSPM;
#endif
{
rpc_transfer_syntax_t IDL_transfer_syntax;
rpc_iovector_elt_t IDL_outs;
volatile ndr_ulong_int IDL_fault_code=error_status_ok;
volatile ndr_ulong_int IDL_user_fault_id;
volatile RPC_SS_THREADS_CANCEL_STATE_T IDL_async_cancel_state;
IDL_ms_t IDL_ms;
idl_byte IDL_stack_packet[IDL_STACK_PACKET_SIZE];
rpc_void_p_t IDL_param_vec[13];

RPC_SS_INIT_CLIENT
RPC_SS_THREADS_DISABLE_ASYNC(IDL_async_cancel_state);
rpc_ss_init_marsh_state(IDL_type_vec, &IDL_ms);
IDL_ms.IDL_stack_packet_status = IDL_stack_packet_unused_k;
IDL_ms.IDL_stack_packet_addr = IDL_stack_packet;
TRY
IDL_ms.IDL_call_h = 0;
IDL_ms.IDL_elt_p = NULL;
IDL_ms.IDL_offset_vec = IDL_offset_vec;
IDL_ms.IDL_rtn_vec = IDL_rtn_vec;
IDL_param_vec[1] = (rpc_void_p_t)&hBinding;
IDL_param_vec[2] = (rpc_void_p_t)&flag_1;
IDL_param_vec[3] = (rpc_void_p_t)&flag_2;
IDL_param_vec[4] = (rpc_void_p_t)&flag_3;
IDL_param_vec[5] = (rpc_void_p_t)&flag_4;
IDL_param_vec[6] = (rpc_void_p_t)&flag_5;
IDL_param_vec[7] = (rpc_void_p_t)&flag_6;
IDL_param_vec[8] = (rpc_void_p_t)&flag_7;
IDL_param_vec[9] = (rpc_void_p_t)&flag_8;
IDL_param_vec[10] = (rpc_void_p_t)&think_time;
IDL_param_vec[11] = (rpc_void_p_t)&auth_lvl;
IDL_param_vec[12] = (rpc_void_p_t)CSPM;
IDL_ms.IDL_param_vec = IDL_param_vec;
IDL_ms.IDL_side = IDL_client_side_k;
IDL_ms.IDL_language = IDL_lang_c_k;
rpc_call_start((rpc_binding_handle_t) hBinding, 0,
 (rpc_if_handle_t)&IDL_ifspec,7,(rpc_call_handle_t*)&IDL_ms.IDL_call_h,&IDL_transfer_syntax,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok) goto IDL_closedown;
rpc_ss_ndr_marsh_interp(
    10,
    732,
    IDL_param_vec, &IDL_ms);
IDL_ms.IDL_elt_p = &IDL_outs;
rpc_call_transceive((rpc_call_handle_t)IDL_ms.IDL_call_h,(rpc_iovector_p_t)&IDL_ms.IDL_iovec,
  IDL_ms.IDL_elt_p,&IDL_ms.IDL_drep,(unsigned32*)&IDL_ms.IDL_status);
if (IDL_ms.IDL_status != error_status_ok)
{
IDL_ms.IDL_elt_p = NULL;
goto IDL_closedown;
}
rpc_ss_ndr_unmar_interp(
    1,
    812,
    IDL_param_vec, &IDL_ms);
IDL_closedown: ;
CATCH(rpc_x_ss_pipe_comm_error)
FINALLY
rpc_ss_ndr_clean_up(&IDL_ms);
rpc_ss_call_end_2((rpc_call_handle_t *)&IDL_ms.IDL_call_h,&IDL_fault_code,&IDL_user_fault_id,&IDL_ms.IDL_status);
if (IDL_ms.IDL_mem_handle.memory)
{
 rpc_ss_mem_free(&IDL_ms.IDL_mem_handle);
}
rpc_ss_report_error_2(IDL_fault_code,IDL_user_fault_id,IDL_ms.IDL_status,
 (RPC_SS_THREADS_CANCEL_STATE_T *)&IDL_async_cancel_state, NULL, NULL, NULL, &IDL_ms);
RPC_SS_THREADS_RESTORE_ASYNC(IDL_async_cancel_state);
ENDTRY
}
#ifdef VMS
#pragma standard
#endif
