<!--
# @OSF_COPYRIGHT@
# 
# 
# HISTORY
# $Log: 3o_example_02.idl,v $
# Revision 1.1.2.2  1996/11/05  20:11:51  weir
# 	Cleaned up history
# 	[1996/11/05  20:10:57  weir]
#
# Revision 1.1.2.1  1996/10/28  19:46:24  wardr
# 	{edit,R1.2.2}
# 	Initial checkin after sgml conversion
# 	[1996/10/28  19:45:57  wardr]
# 
# Revision 1.1.1.2  1996/10/28  19:45:57  wardr
# 	{edit,R1.2.2}
# 	Initial checkin after sgml conversion
# 
# $EndLog$
-->
<!---->
<!-- Fragment document type declaration subset:
ArborText, Inc., 1988-1993, v.4001
<!DOCTYPE Book PUBLIC "-//Davenport//DTD DocBook V2.4//EN" [
]>
-->
<!--  -->
<!--  -->
<!-- COPYRIGHT NOTICE -->
<!-- Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc. -->
<!-- ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the -->
<!-- src directory for the full copyright text. -->
<!--  -->
<!--  -->
<!-- HISTORY -->
<!--  -->
<!-- Revision 1.1.4.3  1993/01/29  17:19:10  cjd -->
<!-- 	Embedded copyright notice -->
<!-- 	[1993/01/29  17:02:54  cjd] -->
<!--  -->
<!-- Revision 1.1.4.2  1992/09/01  16:30:02  weir -->
<!-- 	Moved -->
<!-- 	[1992/09/01  16:22:00  weir] -->
<!--  -->
<!-- Revision 1.1.2.2  1992/03/06  16:32:58  steiner -->
<!-- 	replaced comment leader -->
<!-- 	[1992/03/06  15:41:21  steiner] -->
<!--  -->
<!-- Revision 1.1  1992/01/29  15:40:47  damon -->
<!-- 	Initial revision -->
<!--  -->
<!--  -->
[
uuid(3d6ead56-06e3-11ca-8dd1-826901beabcd),
version(1.0)
]
interface greetif
{

}
