.nL
.ne 20
/****************************************************************************/
/* [27.VI.94]                                                               */
/*                                                                          */
/* sample_bind.idl --                                                       */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*                            -77 cols-                                     */
/****************************************************************************/


[
uuid(006868ca-6064-1d49-9829-0000c0d4de56),
version(1.0)
]
interface sample_bind
{

	void rs_bind_to_object(
		[in] handle_t binding,
		[in, string] char *component,
		[out] uuid_t *object_uuid, 
		[out] uuid_t *mgr_type_uuid,
		[out] error_status_t *status
	);
}

