/****************************************************************************/
/* [27.VI.94]                                                               */
/*                                                                          */
/* sample.idl --                                                            */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*                            -77 cols-                                     */
/****************************************************************************/



[
uuid(002d70b2-671b-1d24-a1da-0000c0d4de56),
version(1.0)
]
interface sample
{

	const long int TEXT_SIZE = 100;


	void sample_call(
		[in] handle_t binding,
		[out] long *status,
		[in,out] error_status_t *remote_status);

.nL
.ne 10
	void sample_get_text(
		[in] handle_t binding,
		[in] uuid_t object_uuid,
		[in,out,string] char text[TEXT_SIZE],
		[out] long *status,
		[in,out] error_status_t *remote_status);

	void sample_put_text(
		[in] handle_t binding,
		[in] uuid_t object_uuid,
		[in,out,string] char text[TEXT_SIZE],
		[out] long *status,
		[in,out] error_status_t *remote_status);


}

