/* Generated by IDL compiler version OSF DCE T1.1.0-03 */
#ifdef VMS
#pragma nostandard
#endif
#include <cmr_idl.h>
#include <dce/idlddefs.h>
static idl_ulong_int IDL_offset_vec[] = {
0,
sizeof(MESSG_DATA_IDL ),
offsetof(MESSG_DATA_IDL , sender_host),
offsetof(MESSG_DATA_IDL , addressee_host),
offsetof(MESSG_DATA_IDL , message_text),
offsetof(MESSG_DATA_IDL , message_count),
offsetof(MESSG_DATA_IDL , transaction_type),
sizeof(MESSG_QUERY_IDL ),
offsetof(MESSG_QUERY_IDL , sender_host),
offsetof(MESSG_QUERY_IDL , message_count),
0
};

static void (*IDL_rtn_vec[])() = {
(void (*)())NULL,
(void (*)())NULL
};

static idl_byte IDL_type_vec[] = {
0xff,0xff,0xff,0xff,
1,
0,
0xff,0xff,
0x03,0x00,
0x01,0x00,
0x00,0x00,
0x00,0x00,
0x24,0x2e,0x4a,0x33,
0x00,0x00,
0x00,0x00,
0x0d,
0x00,
0x55,0x51,0x21,0x20,0x00,0x02,
0x00,0x00,0x00,0x00,
0x04,0x00,0x00,0x00,
0x68,0x01,0x00,0x00,
0xff,0xff,0xff,0xff,
0xff,0xff,0xff,0xff,
0xff,0xff,0xff,0xff,
0xff,0xff,0xff,0xff,
0x03,0x00,0x00,0x00,
0x02,0x00,0x00,0x00,
0x04,0x00,0x00,0x00,
0x02,0x00,0x00,0x00,
0x88,0x00,0x00,0x00,
0x02,0x00,0x00,0x00,
0x88,0x00,0x00,0x00,
0x02,0x00,0x00,0x00,
0x04,0x00,0x00,0x00,
0x02,0x00,0x00,0x00,
0xa0,0x00,0x00,0x00,
0x02,0x00,0x00,0x00,
0xa0,0x00,0x00,0x00,
0x02,0x00,0x00,0x00,
0x02,0x00,0x00,0x00,
0x00,0x00,0x00,0x00,
0xff,0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
0xff,0xff,0xff,0xff,
0x02,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,
0x03,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_FIXED_STRUCT,
0|IDL_PROP_DEP_CHAR|IDL_PROP_DEP_INT,
0xff,
0xb8,0x00,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x02,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_USHORT,
IDL_DT_EOL,
0xff,
0x03,0x00,0x00,0x00,
IDL_DT_PASSED_BY_REF,
IDL_DT_FIXED_STRUCT,
0|IDL_PROP_DEP_CHAR|IDL_PROP_DEP_INT,
0xff,
0xcc,0x00,0x00,0x00,
IDL_DT_EOL,
0xff,0xff,0xff,
0x07,0x00,0x00,0x00,
IDL_DT_NDR_ALIGN_4,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0x4b,0x01,0x00,0x00,
0x4b,0x01,0x00,0x00,
IDL_DT_LONG,
IDL_DT_EOL,
0xff,0xff,
0x01,0x00,0x00,0x00,
IDL_DT_NDR_ALIGN_4,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0x2f,0x01,0x00,0x00,
0x2f,0x01,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0x13,0x01,0x00,0x00,
0x13,0x01,0x00,0x00,
IDL_DT_STRING,
IDL_DT_VARYING_ARRAY,
0|IDL_PROP_DEP_CHAR,
0xff,
0xf7,0x00,0x00,0x00,
0xf7,0x00,0x00,0x00,
IDL_DT_LONG,
IDL_DT_LONG,
IDL_DT_EOL,
1,
0x00,0x00,0x00,0x00,
0x4f,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x0b,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x0b,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,
1,
0x00,0x00,0x00,0x00,
0x0b,0x00,0x00,0x00,
IDL_LIMIT_FIXED,
0xff,0xff,0xff,
0x00,0x00,0x00,0x00,
IDL_LIMIT_STRING,
1,
0xff,0xff,
0xff,0xff,0xff,0xff,
IDL_DT_CHAR,
0xff,0xff,0xff,
0x00,0x00,0x00,0x10,
0
};


static MSG_SLAVE_v0_0_epv_t IDL_manager_epv = {
QUERY_STUB
,MESSAGE_STUB
,KILL_MSG
};

static void op0_ssr
#ifdef IDL_PROTOTYPES
(
 handle_t hBinding,
 rpc_call_handle_t IDL_call_h,
 rpc_iovector_elt_p_t IDL_elt_p,
 ndr_format_p_t IDL_drep_p,
 rpc_transfer_syntax_p_t IDL_transfer_syntax_p,
 rpc_mgr_epv_t IDL_mgr_epv,
 error_status_t *IDL_status_p
)
#else
(hBinding, IDL_call_h, IDL_elt_p, IDL_drep_p, IDL_transfer_syntax_p, IDL_mgr_epv, IDL_status_p)
 handle_t hBinding;
 rpc_call_handle_t IDL_call_h;
 rpc_iovector_elt_p_t IDL_elt_p;
 ndr_format_p_t IDL_drep_p;
 rpc_transfer_syntax_p_t IDL_transfer_syntax_p;
 rpc_mgr_epv_t IDL_mgr_epv;
 error_status_t *IDL_status_p;
#endif
{
IDL_ms_t IDL_ms;
volatile ndr_boolean IDL_manager_entered = ndr_false;
volatile RPC_SS_THREADS_CANCEL_STATE_T IDL_general_cancel_state;
idl_byte IDL_stack_packet[IDL_STACK_PACKET_SIZE];
rpc_void_p_t IDL_param_vec[4];
idl_ushort_int qmsg_buf_len;
MESSG_QUERY_IDL qmsg_buf;
RPC_SS_INIT_SERVER
rpc_ss_init_marsh_state(IDL_type_vec, &IDL_ms);
IDL_ms.IDL_stack_packet_status = IDL_stack_packet_unused_k;
IDL_ms.IDL_stack_packet_addr = IDL_stack_packet;
TRY
IDL_ms.IDL_offset_vec = IDL_offset_vec;
IDL_ms.IDL_rtn_vec = IDL_rtn_vec;
IDL_ms.IDL_call_h = (volatile rpc_call_handle_t)IDL_call_h;
IDL_ms.IDL_drep = *IDL_drep_p;
IDL_ms.IDL_elt_p = IDL_elt_p;
IDL_param_vec[1] = (rpc_void_p_t)&hBinding;
IDL_param_vec[2] = (rpc_void_p_t)&qmsg_buf_len;
IDL_param_vec[3] = (rpc_void_p_t)&qmsg_buf;
IDL_ms.IDL_param_vec = IDL_param_vec;
IDL_ms.IDL_side = IDL_server_side_k;
IDL_ms.IDL_language = IDL_lang_c_k;
rpc_ss_ndr_unmar_interp(
    2,
    136,
    IDL_param_vec, &IDL_ms);

/* manager call */
IDL_manager_entered = ndr_true;
RPC_SS_THREADS_ENABLE_GENERAL(IDL_general_cancel_state);
(*((MSG_SLAVE_v0_0_epv_t *)IDL_mgr_epv)->QUERY_STUB)(hBinding,
    &qmsg_buf_len,
    &qmsg_buf);
RPC_SS_THREADS_RESTORE_GENERAL(IDL_general_cancel_state);
{
rpc_ss_ndr_marsh_interp(
    2,
    136,
    IDL_param_vec, &IDL_ms);
if (IDL_ms.IDL_iovec.num_elt != 0)
  rpc_call_transmit((rpc_call_handle_t)IDL_ms.IDL_call_h,(rpc_iovector_p_t)&IDL_ms.IDL_iovec,
  (unsigned32*)&IDL_ms.IDL_status);  /* Send remaining outs */

}
IDL_closedown: ;
CATCH_ALL
rpc_ss_ndr_clean_up(&IDL_ms);
if (!RPC_SS_EXC_MATCHES(THIS_CATCH,&rpc_x_ss_pipe_comm_error))
{
if ( ! IDL_manager_entered )
{
}
{
rpc_ss_send_server_exception_2(IDL_call_h,THIS_CATCH,0,NULL,&IDL_ms);
IDL_ms.IDL_status = error_status_ok;
}
}
ENDTRY
if (IDL_ms.IDL_mem_handle.memory)
{
 rpc_ss_mem_free(&IDL_ms.IDL_mem_handle);
}
if (IDL_ms.IDL_status != error_status_ok)
{
if (IDL_ms.IDL_status == rpc_s_call_cancelled)
{
rpc_ss_send_server_exception(IDL_call_h,&RPC_SS_THREADS_X_CANCELLED);
IDL_ms.IDL_status = error_status_ok;
}
else
{
{
rpc_ss_send_server_exception(IDL_call_h,&rpc_x_ss_remote_comm_failure);
IDL_ms.IDL_status = error_status_ok;
}
}
}
*IDL_status_p = IDL_ms.IDL_status;
}

static void op1_ssr
#ifdef IDL_PROTOTYPES
(
 handle_t hBinding,
 rpc_call_handle_t IDL_call_h,
 rpc_iovector_elt_p_t IDL_elt_p,
 ndr_format_p_t IDL_drep_p,
 rpc_transfer_syntax_p_t IDL_transfer_syntax_p,
 rpc_mgr_epv_t IDL_mgr_epv,
 error_status_t *IDL_status_p
)
#else
(hBinding, IDL_call_h, IDL_elt_p, IDL_drep_p, IDL_transfer_syntax_p, IDL_mgr_epv, IDL_status_p)
 handle_t hBinding;
 rpc_call_handle_t IDL_call_h;
 rpc_iovector_elt_p_t IDL_elt_p;
 ndr_format_p_t IDL_drep_p;
 rpc_transfer_syntax_p_t IDL_transfer_syntax_p;
 rpc_mgr_epv_t IDL_mgr_epv;
 error_status_t *IDL_status_p;
#endif
{
IDL_ms_t IDL_ms;
volatile ndr_boolean IDL_manager_entered = ndr_false;
volatile RPC_SS_THREADS_CANCEL_STATE_T IDL_general_cancel_state;
idl_byte IDL_stack_packet[IDL_STACK_PACKET_SIZE];
rpc_void_p_t IDL_param_vec[4];
idl_ushort_int msg_buf_len;
MESSG_DATA_IDL msg_buf;
RPC_SS_INIT_SERVER
rpc_ss_init_marsh_state(IDL_type_vec, &IDL_ms);
IDL_ms.IDL_stack_packet_status = IDL_stack_packet_unused_k;
IDL_ms.IDL_stack_packet_addr = IDL_stack_packet;
TRY
IDL_ms.IDL_offset_vec = IDL_offset_vec;
IDL_ms.IDL_rtn_vec = IDL_rtn_vec;
IDL_ms.IDL_call_h = (volatile rpc_call_handle_t)IDL_call_h;
IDL_ms.IDL_drep = *IDL_drep_p;
IDL_ms.IDL_elt_p = IDL_elt_p;
IDL_param_vec[1] = (rpc_void_p_t)&hBinding;
IDL_param_vec[2] = (rpc_void_p_t)&msg_buf_len;
IDL_param_vec[3] = (rpc_void_p_t)&msg_buf;
IDL_ms.IDL_param_vec = IDL_param_vec;
IDL_ms.IDL_side = IDL_server_side_k;
IDL_ms.IDL_language = IDL_lang_c_k;
rpc_ss_ndr_unmar_interp(
    2,
    160,
    IDL_param_vec, &IDL_ms);

/* manager call */
IDL_manager_entered = ndr_true;
RPC_SS_THREADS_ENABLE_GENERAL(IDL_general_cancel_state);
(*((MSG_SLAVE_v0_0_epv_t *)IDL_mgr_epv)->MESSAGE_STUB)(hBinding,
    &msg_buf_len,
    &msg_buf);
RPC_SS_THREADS_RESTORE_GENERAL(IDL_general_cancel_state);
{
rpc_ss_ndr_marsh_interp(
    2,
    160,
    IDL_param_vec, &IDL_ms);
if (IDL_ms.IDL_iovec.num_elt != 0)
  rpc_call_transmit((rpc_call_handle_t)IDL_ms.IDL_call_h,(rpc_iovector_p_t)&IDL_ms.IDL_iovec,
  (unsigned32*)&IDL_ms.IDL_status);  /* Send remaining outs */

}
IDL_closedown: ;
CATCH_ALL
rpc_ss_ndr_clean_up(&IDL_ms);
if (!RPC_SS_EXC_MATCHES(THIS_CATCH,&rpc_x_ss_pipe_comm_error))
{
if ( ! IDL_manager_entered )
{
}
{
rpc_ss_send_server_exception_2(IDL_call_h,THIS_CATCH,0,NULL,&IDL_ms);
IDL_ms.IDL_status = error_status_ok;
}
}
ENDTRY
if (IDL_ms.IDL_mem_handle.memory)
{
 rpc_ss_mem_free(&IDL_ms.IDL_mem_handle);
}
if (IDL_ms.IDL_status != error_status_ok)
{
if (IDL_ms.IDL_status == rpc_s_call_cancelled)
{
rpc_ss_send_server_exception(IDL_call_h,&RPC_SS_THREADS_X_CANCELLED);
IDL_ms.IDL_status = error_status_ok;
}
else
{
{
rpc_ss_send_server_exception(IDL_call_h,&rpc_x_ss_remote_comm_failure);
IDL_ms.IDL_status = error_status_ok;
}
}
}
*IDL_status_p = IDL_ms.IDL_status;
}

static void op2_ssr
#ifdef IDL_PROTOTYPES
(
 handle_t hBinding,
 rpc_call_handle_t IDL_call_h,
 rpc_iovector_elt_p_t IDL_elt_p,
 ndr_format_p_t IDL_drep_p,
 rpc_transfer_syntax_p_t IDL_transfer_syntax_p,
 rpc_mgr_epv_t IDL_mgr_epv,
 error_status_t *IDL_status_p
)
#else
(hBinding, IDL_call_h, IDL_elt_p, IDL_drep_p, IDL_transfer_syntax_p, IDL_mgr_epv, IDL_status_p)
 handle_t hBinding;
 rpc_call_handle_t IDL_call_h;
 rpc_iovector_elt_p_t IDL_elt_p;
 ndr_format_p_t IDL_drep_p;
 rpc_transfer_syntax_p_t IDL_transfer_syntax_p;
 rpc_mgr_epv_t IDL_mgr_epv;
 error_status_t *IDL_status_p;
#endif
{
IDL_ms_t IDL_ms;
volatile ndr_boolean IDL_manager_entered = ndr_false;
volatile RPC_SS_THREADS_CANCEL_STATE_T IDL_general_cancel_state;
idl_byte IDL_stack_packet[IDL_STACK_PACKET_SIZE];
rpc_void_p_t IDL_param_vec[2];
RPC_SS_INIT_SERVER
rpc_ss_init_marsh_state(IDL_type_vec, &IDL_ms);
IDL_ms.IDL_stack_packet_status = IDL_stack_packet_unused_k;
IDL_ms.IDL_stack_packet_addr = IDL_stack_packet;
TRY
IDL_ms.IDL_offset_vec = IDL_offset_vec;
IDL_ms.IDL_rtn_vec = IDL_rtn_vec;
IDL_ms.IDL_call_h = (volatile rpc_call_handle_t)IDL_call_h;
IDL_ms.IDL_drep = *IDL_drep_p;
IDL_ms.IDL_elt_p = IDL_elt_p;
IDL_param_vec[1] = (rpc_void_p_t)&hBinding;
IDL_ms.IDL_param_vec = IDL_param_vec;
IDL_ms.IDL_side = IDL_server_side_k;
IDL_ms.IDL_language = IDL_lang_c_k;
rpc_ss_ndr_unmar_interp(
    0,
    0,
    IDL_param_vec, &IDL_ms);

/* manager call */
IDL_manager_entered = ndr_true;
RPC_SS_THREADS_ENABLE_GENERAL(IDL_general_cancel_state);
(*((MSG_SLAVE_v0_0_epv_t *)IDL_mgr_epv)->KILL_MSG)(hBinding);
RPC_SS_THREADS_RESTORE_GENERAL(IDL_general_cancel_state);
{
rpc_ss_ndr_marsh_interp(
    0,
    0,
    IDL_param_vec, &IDL_ms);
if (IDL_ms.IDL_iovec.num_elt != 0)
  rpc_call_transmit((rpc_call_handle_t)IDL_ms.IDL_call_h,(rpc_iovector_p_t)&IDL_ms.IDL_iovec,
  (unsigned32*)&IDL_ms.IDL_status);  /* Send remaining outs */

}
IDL_closedown: ;
CATCH_ALL
rpc_ss_ndr_clean_up(&IDL_ms);
if (!RPC_SS_EXC_MATCHES(THIS_CATCH,&rpc_x_ss_pipe_comm_error))
{
if ( ! IDL_manager_entered )
{
}
{
rpc_ss_send_server_exception_2(IDL_call_h,THIS_CATCH,0,NULL,&IDL_ms);
IDL_ms.IDL_status = error_status_ok;
}
}
ENDTRY
if (IDL_ms.IDL_mem_handle.memory)
{
 rpc_ss_mem_free(&IDL_ms.IDL_mem_handle);
}
if (IDL_ms.IDL_status != error_status_ok)
{
if (IDL_ms.IDL_status == rpc_s_call_cancelled)
{
rpc_ss_send_server_exception(IDL_call_h,&RPC_SS_THREADS_X_CANCELLED);
IDL_ms.IDL_status = error_status_ok;
}
else
{
{
rpc_ss_send_server_exception(IDL_call_h,&rpc_x_ss_remote_comm_failure);
IDL_ms.IDL_status = error_status_ok;
}
}
}
*IDL_status_p = IDL_ms.IDL_status;
}

static rpc_v2_server_stub_proc_t IDL_epva[] = 
{
 (rpc_v2_server_stub_proc_t)op0_ssr,
 (rpc_v2_server_stub_proc_t)op1_ssr,
 (rpc_v2_server_stub_proc_t)op2_ssr
};

static rpc_syntax_id_t IDL_transfer_syntaxes[1] = {
{
{0x8a885d04, 0x1ceb, 0x11c9, 0x9f, 0xe8, {0x8, 0x0, 0x2b, 0x10, 0x48, 0x60}},
2}};

static rpc_if_rep_t IDL_ifspec = {
  1, /* ifspec rep version */
  3, /* op count */
  0, /* if version */
  {0x334a2e24, 0x0000, 0x0000, 0x0d, 0x00, {0x55, 0x51, 0x21, 0x20, 0x0, 0x2}},
  2, /* stub/rt if version */
  {0, NULL}, /* endpoint vector */
  {1, IDL_transfer_syntaxes} /* syntax vector */
,IDL_epva /* server_epv */
,(rpc_mgr_epv_t)&IDL_manager_epv /* manager epv */
};
/* global */ rpc_if_handle_t MSG_SLAVE_v0_0_s_ifspec = (rpc_if_handle_t)&IDL_ifspec;
#ifdef VMS
#pragma standard
#endif
