/* Generated by IDL compiler version OSF DCE T1.1.0-03 */
#ifndef pos_def_v0_0_included
#define pos_def_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
typedef struct _MESSG_DATA_IDL {
idl_char sender_host[12];
idl_char addressee_host[12];
idl_char message_text[80];
idl_long_int message_count;
idl_long_int transaction_type;
} MESSG_DATA_IDL;
typedef struct _MESSG_QUERY_IDL {
idl_char sender_host[12];
idl_long_int message_count;
} MESSG_QUERY_IDL;

#ifdef __cplusplus
    }
#endif

#endif
