[pointer_default(ptr)] interface pos_def
{


  typedef struct _MESSG_DATA_IDL
  {
    [string]      char       sender_host[12];
    [string]      char       addressee_host[12];
    [string]      char       message_text[80];
                  long       message_count;
                  long       transaction_type;
  } MESSG_DATA_IDL;

  typedef struct _MESSG_QUERY_IDL
  {
    [string]      char       sender_host[12];
                  long       message_count;
  } MESSG_QUERY_IDL;


}
