/****************************************************************************
 * Client IDL for distributed application
 *
 *
 *
 *
 *                                                  IBM Corporation
 *                                                  LAN Systems Perofrmance
 *                                                  Bob Russell Internal 9151
 *                                                  11400 Burnet Rd
 *                                                  Austin, Texas 78758
 ****************************************************************************/


[
    uuid(334A2E24-0000-0000-0D00-555121200000),
    version(0)
]

interface Howdy
{
   /*
    * The following imports the structure definitions. The definitions
    * must be included in the IDL for the cross-platform byte reversal
    * to be handled automatically by RPC.
    */
    import "pos_def.idl";

    [idempotent]
    void rpc_QUERY_MSG
    (
        [in]  handle_t                           hBinding,
        [in, out] unsigned short                *qmsg_buf_len,
        [in, out] MESSG_QUERY_IDL               *qmsg_buf
    );

    [idempotent]
    void rpc_MESSAGE
    (
        [in]      handle_t                       hBinding,
        [in, out] unsigned short                *msg_buf_len,
        [in, out] MESSG_DATA_IDL                *msg_buf
    );


    [idempotent]                     /* Server Stop Listening */
    void rpc_KILL
    (
        [in] handle_t                           hBinding
    );

}
