/* Generated by IDL compiler version OSF DCE T1.1.0-03 */
#ifndef Howdy_v0_0_included
#define Howdy_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef pos_def_v0_0_included
#include <pos_def.h>
#endif
extern void rpc_QUERY_MSG(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding,
    /* [in, out] */ idl_ushort_int *qmsg_buf_len,
    /* [in, out] */ MESSG_QUERY_IDL *qmsg_buf
#endif
);
extern void rpc_MESSAGE(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding,
    /* [in, out] */ idl_ushort_int *msg_buf_len,
    /* [in, out] */ MESSG_DATA_IDL *msg_buf
#endif
);
extern void rpc_KILL(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding
#endif
);
typedef struct Howdy_v0_0_epv_t {
void (*rpc_QUERY_MSG)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding,
    /* [in, out] */ idl_ushort_int *qmsg_buf_len,
    /* [in, out] */ MESSG_QUERY_IDL *qmsg_buf
#endif
);
void (*rpc_MESSAGE)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding,
    /* [in, out] */ idl_ushort_int *msg_buf_len,
    /* [in, out] */ MESSG_DATA_IDL *msg_buf
#endif
);
void (*rpc_KILL)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t hBinding
#endif
);
} Howdy_v0_0_epv_t;
extern rpc_if_handle_t Howdy_v0_0_c_ifspec;
extern rpc_if_handle_t Howdy_v0_0_s_ifspec;

#ifdef __cplusplus
    }
#endif

#endif
